# -*- coding: utf-8 -*-
"""fullflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWbhIM22GnureUahwtsanS0T603KRQ7f

# PHẦN I: DỮ LIỆU
"""

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/LuanVan/data/raw_first-week-of-dec-2025/"

import pandas as pd

df_nodes = pd.read_csv(folder_path + "nodes_full.csv")
df_nodes_pruned = pd.read_csv(folder_path + "nodes_full_pruned.csv")
df_edges = pd.read_csv(folder_path + "edges_weighted.csv")

print(f"Number of nodes: {len(df_nodes)}")
print(f"Number of pruned nodes: {len(df_nodes_pruned)}")
print(f"Number of edges: {len(df_edges)}")

df_nodes.columns

df_edges.columns

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import numpy as np
import warnings

# Dữ liệu số lượng Node
node_counts = [len(df_nodes), len(df_nodes_pruned)]
labels = ['Trước khi cắt tỉa', 'Sau khi cắt tỉa']

plt.figure(figsize=(8, 6))
# Sử dụng barplot của seaborn để có màu sắc đẹp
ax = sns.barplot(x=labels, y=node_counts, palette=['#e74c3c', '#2ecc71'])

max_val = max(node_counts)
plt.ylim(0, max_val * 1.25) # Tăng thêm 25% không gian phía trên đỉnh cột cao nhất

# Cấu hình tiêu đề và trục
plt.title('Số lượng nodes trước và sau khi cắt tỉa', fontsize=15, weight='bold', pad=10)
plt.ylabel('Số lượng Nodes', fontsize=12)

# Thêm con số hiển thị trực tiếp trên đầu mỗi cột
for i, v in enumerate(node_counts):
    ax.text(i, v + 5, str(v), color='black', ha='center', fontweight='bold', fontsize=13)

# Thêm text box chú thích về số lượng node bị loại bỏ
removed_nodes = node_counts[0] - node_counts[1]
# plt.text(0.8, 0.92, f"Đã loại bỏ {removed_nodes} nodes cô lập",
#          transform=ax.transAxes, ha='center', fontsize=11,
#          bbox=dict(facecolor='white', alpha=0.9, edgecolor='#7f8c8d', boxstyle='round,pad=0.5'))

plt.tight_layout()
plt.show()

"""> Trực quan hóa tỷ lệ 4 Layer (Similarity, Co-Owner, Follow, Interact)"""

# BIỂU ĐỒ DONUT TỶ LỆ CÁC LAYER (EDGE TYPES)
layer_counts = df_edges['layer'].value_counts()
colors = ['#9b59b6', '#e74c3c', '#3498db', '#2ecc71'] # Tím(Sim), Đỏ(Co-own), Xanh(Fol), Xanh lá(Int)
explode = (0.05, 0.05, 0.05, 0.05)

plt.figure(figsize=(8, 8))
plt.pie(layer_counts, labels=layer_counts.index, autopct='%1.1f%%', startangle=140,
        colors=colors, explode=explode, textprops={'fontsize': 12, 'weight': 'bold'})
# Tạo vòng tròn trắng ở giữa để làm Donut Chart
centre_circle = plt.Circle((0,0),0.70,fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

plt.title('Phân bố quan hệ trong tầng tương tác', fontsize=16, pad=20)
plt.show()

"""> Biểu đồ phân bố bậc (Degree Distribution)"""

# Tạo đồ thị từ danh sách pruned nodes và edges
G = nx.MultiDiGraph()
G.add_nodes_from(df_nodes_pruned['profile_id'].tolist())
for _, row in df_edges.iterrows():
    if G.has_node(row['source']) and G.has_node(row['target']):
        G.add_edge(row['source'], row['target'], layer=row['layer'])

# Tính toán các chỉ số Topo
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()
density = nx.density(G)

# Dùng DiGraph đơn giản để tính Clustering (MultiGraph không hỗ trợ tính toán này)
G_simple = nx.Graph(G)
avg_clustering = nx.average_clustering(G_simple)

print(f"Số lượng Node thực tế liên kết: {num_nodes}")
print(f"Số lượng Cạnh: {num_edges}")
print(f"Mật độ đồ thị (Density): {density:.5f}")
print(f"Hệ số cụm trung bình (Avg Clustering Coefficient): {avg_clustering:.4f}")

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd

# VẼ BIỂU ĐỒ PHÂN BỐ BẬC (LOG-LOG DEGREE DISTRIBUTION)
degrees = [degree for node, degree in G.degree()]
degree_counts = pd.Series(degrees).value_counts().sort_index()

plt.figure(figsize=(10, 6))
ax = plt.gca() # Lấy đối tượng trục hiện tại để tùy chỉnh sâu

plt.plot(degree_counts.index, degree_counts.values, color='#34495e', linestyle='-', linewidth=2, alpha=0.4, zorder=2)
plt.scatter(degree_counts.index, degree_counts.values, color='#e67e22', alpha=0.8, edgecolors='k', s=60, zorder=3)

# Chuyển sang thang đo Logarit
plt.xscale('log')
plt.yscale('log')

formatter = ticker.ScalarFormatter()
formatter.set_scientific(False)
ax.xaxis.set_major_formatter(formatter)
ax.yaxis.set_major_formatter(formatter)

# Khai báo cụ thể các mốc giá trị muốn hiển thị trên trục X và Y
x_ticks = [1, 2, 5, 10, 20, 50, 100]
y_ticks = [1, 2, 5, 10, 20, 50]

plt.xticks(x_ticks, labels=[str(x) for x in x_ticks])
plt.yticks(y_ticks, labels=[str(y) for y in y_ticks])

# Chỉnh lưới (Grid) hiển thị cả nét đứt cho các giá trị nhỏ
plt.grid(True, which="major", ls="-", alpha=0.6, color='gray')
plt.grid(True, which="minor", ls=":", alpha=0.3, color='gray')

# Làm đẹp các thành phần khác
plt.title('Phân bố bậc của đồ thị (Log-Log Scale)', fontsize=15, weight='bold', pad=15)
plt.xlabel('Bậc của Node', fontsize=12, weight='bold')
plt.ylabel('Tần suất', fontsize=12, weight='bold')

plt.tight_layout()
plt.show()

"""> Trực quan hóa Đặc trưng Dữ liệu Bất thường"""

fig, ax = plt.subplots(1, 1, figsize=(8, 6))

# Biểu đồ Phân bố Ví thao túng (Sybil Wallets)
wallet_counts = df_nodes['owned_by'].value_counts()
sybil_wallets = wallet_counts[wallet_counts > 1]
# Nhóm các ví lại để xem có bao nhiêu ví sở hữu 2, 3, 4... tài khoản
wallet_distribution = sybil_wallets.value_counts().sort_index()

sns.barplot(x=wallet_distribution.index, y=wallet_distribution.values, ax=ax, palette='viridis') # Sử dụng 'ax' cho subplot duy nhất
ax.set_title('Phân bố các Ví sở hữu nhiều tài khoản (Co-Owner)', fontsize=13, weight='bold')
ax.set_xlabel('Số tài khoản được sở hữu bởi 1 Ví')
ax.set_ylabel('Số lượng Ví')
ax.set_xticks(range(len(wallet_distribution)))
ax.set_xticklabels([int(x) for x in wallet_distribution.index])

plt.tight_layout()
plt.show()

"""> Phân bố số lượng tài khoản được tạo theo thời gian"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Chuyển đổi cột 'created_on' sang định dạng Datetime
df_nodes['created_on_dt'] = pd.to_datetime(df_nodes['created_on'])
creation_times = df_nodes['created_on_dt'].dt.floor('8H').value_counts().sort_index()

# Làm đẹp lại nhãn trục X (Chỉ lấy Ngày/Tháng và Giờ, ví dụ: "01/12 18:00")
formatted_labels = creation_times.index.strftime('%d/%m %H:%M')

plt.figure(figsize=(14, 5))

# Vẽ biểu đồ
ax = sns.barplot(x=formatted_labels, y=creation_times.values, color='#3498db')

# Hiển thị tất cả các nhãn (vì số cột đã giảm, không cần giấu đi nữa)
plt.xticks(rotation=45, ha='right', fontsize=10)

plt.title('Phân bố số lượng tài khoản được tạo theo thời gian - Khung 8 Giờ', fontsize=15, weight='bold', pad=15)
plt.xlabel('Thời gian tạo', fontsize=12)
plt.ylabel('Số lượng tài khoản', fontsize=12)

plt.tight_layout()
plt.show()

"""> Phân bố điểm tin cậy"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.figure(figsize=(9, 5))

# Dùng Histogram kết hợp đường cong KDE (Kernel Density Estimate)
ax = sns.histplot(df_nodes_pruned['trust_score'], bins=30, kde=True, color='#9b59b6', edgecolor='white')

# Kẻ vạch các đường Thống kê
mean_score = df_nodes_pruned['trust_score'].mean()

plt.axvline(mean_score, color='#2ecc71', linestyle='-', linewidth=2, label=f'Trung bình: {mean_score:.2f}')

plt.title('Phân bố Điểm tin cậy của Hệ thống gốc', fontsize=15, weight='bold', pad=15)
plt.xlabel('Trust Score', fontsize=12)
plt.ylabel('Mật độ', fontsize=12)
plt.legend(fontsize=11)

plt.xticks(range(0, 101, 10))
plt.tight_layout()
plt.show()

"""# PHẦN II: Gom cụm với Graph Autoencoder và K-Means"""

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/LuanVan/data/raw_first-week-of-dec-2025/"

import pandas as pd

df_nodes = pd.read_csv(folder_path + "nodes_full_pruned.csv")
df_edges = pd.read_csv(folder_path + "edges_weighted.csv")

print(f"Number of nodes: {len(df_nodes)}")
print(f"Number of edges: {len(df_edges)}")

"""> XỬ LÝ ĐẶC TRƯNG NGỮ NGHĨA (SBERT)"""

from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer('all-MiniLM-L6-v2')

text_data = [
    f"Handle: {h}. Name: {n}. Bio: {b}"
    for h, n, b in zip(df_nodes['handle'], df_nodes['display_name'], df_nodes['bio'])
]

# Encode thành vector (384 chiều)
text_emb = sbert_model.encode(text_data)
print(f"Text Embedding Shape: {text_emb.shape}")

# Quy tắc: 1 nếu có avatar tùy chỉnh, 0 nếu là avatar mặc định/rỗng
def check_avatar(url):
    if not isinstance(url, str) or url == "" or "default" in url.lower():
        return 0
    return 1

img_feat = df_nodes['picture_url'].apply(check_avatar).values.reshape(-1, 1)

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Chuẩn hóa thống kê
df_nodes['created_on'] = pd.to_datetime(df_nodes['created_on'])
df_nodes['days_active'] = (pd.Timestamp.now(tz='UTC') - df_nodes['created_on']).dt.days.fillna(0)
scaler = MinMaxScaler()

stat_cols = [
    'total_tips',
    'total_posts',
    'total_quotes',
    'total_reacted',
    'total_reactions',
    'total_reposts',
    'total_collects',
    'total_comments',
    'total_followers',
    'total_following']

stats_norm = scaler.fit_transform(df_nodes[stat_cols + ['days_active']])

# Tổng hợp
x_np = np.hstack([text_emb, img_feat, stats_norm])
node_ids = df_nodes['profile_id'].values
id_to_idx = {uid: i for i, uid in enumerate(node_ids)}

print(f"-> Xong Features! Kích thước: {x_np.shape}")

import json

with open(folder_path + 'id_to_index.json', 'w') as f:
    json.dump(id_to_idx, f)

print("Đã lưu 'id_to_index.json'")

"""> CHUẨN BỊ DỮ LIỆU HUẤN LUYỆN

Xử lý dữ liệu nodes
"""

!pip install torch_geometric

import pandas as pd
import numpy as np
import torch
import json
import ast
from torch_geometric.data import Data
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sentence_transformers import SentenceTransformer

numeric_cols = [
    'trust_score', 'total_tips', 'total_posts', 'total_quotes',
    'total_reacted', 'total_reactions', 'total_reposts',
    'total_collects', 'total_comments', 'total_followers', 'total_following'
]

df_nodes['created_on'] = pd.to_datetime(df_nodes['created_on'], utc=True) # Thêm utc=True để tránh lỗi timezone
df_nodes['days_active'] = (pd.Timestamp.now(tz='UTC') - df_nodes['created_on']).dt.days.fillna(0)

numeric_cols = numeric_cols + ['days_active']

import joblib

scaler = StandardScaler()
scaled_features = scaler.fit_transform(df_nodes[numeric_cols])

scaler_path = folder_path + 'scaler.bin'
joblib.dump(scaler, scaler_path)

print(f"Đã lưu scaler vào: {scaler_path}")

node_embedding_cols = [f"emb_{i}" for i in range(text_emb.shape[1])]
len(node_embedding_cols)

df_node_embedding = pd.DataFrame(text_emb, columns=node_embedding_cols)
df_node_numeric = pd.DataFrame(scaled_features, columns=[f"num_{col}" for col in numeric_cols])

# Ghép: [Profile_ID] + [Scaled Numbers] + [Text Embeddings]
final_node_df = pd.concat([
    df_nodes[['profile_id']], # Giữ lại ID để map sau này
    df_node_numeric,
    df_node_embedding
], axis=1)

final_node_df.shape

# Bỏ cột profile_id để lấy ma trận features
feature_cols = [c for c in final_node_df.columns if c not in ['profile_id', 'temp_idx']]
x = torch.tensor(final_node_df[feature_cols].values, dtype=torch.float)

x.shape

"""Xử lý dữ liệu cạnh"""

len(df_edges)

# Định nghĩa các layer
DIRECTED_LAYERS = ['Follow', 'Interact']
UNDIRECTED_LAYERS = ['Co-Owner', 'Similarity']

# Tách DataFrame
df_directed = df_edges[df_edges['layer'].isin(DIRECTED_LAYERS)].copy()
df_undirected = df_edges[df_edges['layer'].isin(UNDIRECTED_LAYERS)].copy()

print(f"Số lượng cạnh có hướng: {len(df_directed)}")
print(f"Số lượng cạnh vô hướng: {len(df_undirected)}")

# Xử lý cạnh Vô hướng: Tạo chiều ngược lại (Reverse Edges)
df_undirected_rev = df_undirected.copy()

# Đổi chỗ source và target
df_undirected_rev['source'] = df_undirected['target']
df_undirected_rev['target'] = df_undirected['source']

# Gộp xuôi và ngược lại với nhau => 2 chiều
df_undirected_final = pd.concat([df_undirected, df_undirected_rev], ignore_index=True)

len(df_undirected_final)

# Gộp tất cả lại thành DataFrame cuối cùng
df_edges_final = pd.concat([df_directed, df_undirected_final], ignore_index=True)

# Map ID (Lưu ý map trên df_edges_final)
df_edges_final['source_idx'] = df_edges_final['source'].map(id_to_idx)
df_edges_final['target_idx'] = df_edges_final['target'].map(id_to_idx)
df_edges_final = df_edges_final.dropna(subset=['source_idx', 'target_idx'])

len(df_edges_final)

# Tạo Edge Index
edge_index = torch.tensor([
    df_edges_final['source_idx'].values,
    df_edges_final['target_idx'].values
], dtype=torch.long)

# Tạo Edge Weight (Attribute)
# Chuyển đổi weight sang float
edge_weights = df_edges_final['weight'].values.astype(float)
edge_attr = torch.tensor(edge_weights, dtype=torch.float).view(-1, 1)

# Tạo Data Object
# x là node features đã xử lý từ trước
data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr)

graph_data_path = folder_path + 'graph_data.pt'

torch.save(data, graph_data_path)
print(f"Đã lưu đối tượng data vào: {graph_data_path}")

"""> GAT + GAE - Học không giám sát"""

import torch

data = torch.load(folder_path + 'graph_data.pt', weights_only=False)
print(data)

from torch_geometric.nn import GATConv, GAE
import torch.nn.functional as F
import torch

class GATEncoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()

        self.conv1 = GATConv(
            in_channels,
            32,
            heads=4,
            dropout=0.3,
            edge_dim=1  # edge_dim=1: Để model biết có trọng số cạnh 1 chiều
        )

        # Input channel là 32 * 4 (do 4 heads ở layer 1)
        self.conv2 = GATConv(
            32 * 4,
            out_channels,
            heads=1,
            concat=False,
            dropout=0.3,
            edge_dim=1  # edge_dim=1 để tiếp tục sử dụng trọng số cạnh ở tầng này
        )

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)
        x = self.conv2(x, edge_index, edge_attr=edge_attr)
        return x

in_channels = data.num_features
out_channels = 16

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

from torch_geometric.nn import GAE

model = GAE(GATEncoder(in_channels, out_channels))

model = model.to(device)
data = data.to(device)

print(f"Tổng số tham số: {count_parameters(model)}")
print(model)

optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
nums_epochs = 1000

# CẤU HÌNH EARLY STOPPING
patience = 100          # Số epoch chấp nhận không cải thiện trước khi dừng (thường là 20-50)
min_delta = 0.001      # Ngưỡng cải thiện tối thiểu (để tránh việc giảm li ti 0.000001 mà vẫn tính là giảm)
patience_counter = 0   # Biến đếm số lần không cải thiện liên tiếp

loss_history = []
best = dict(best_epoch=0, best_loss=float('inf'))  # {best_epoch: ..., best_loss: ...}

model.train()
for epoch in range(nums_epochs):
    optimizer.zero_grad()

    z = model.encode(data.x, data.edge_index, edge_attr=data.edge_attr)

    # Calculate Loss (Reconstruction Loss)
    loss = model.recon_loss(z, data.edge_index)

    loss.backward()
    optimizer.step()

    current_loss = loss.item()
    loss_history.append(current_loss)

    # LOGIC EARLY STOPPING & CHECKPOINT
    if current_loss < (best['best_loss'] - min_delta):
        best['best_loss'] = current_loss
        best['best_epoch'] = epoch + 1
        patience_counter = 0 # Reset bộ đếm vì đã tìm thấy kỷ lục mới

        # Lưu model tốt nhất
        best_z = z.detach().cpu().numpy() # Lưu embedding tốt nhất
    else:
        patience_counter += 1

    if (epoch + 1) % 25 == 0 or (epoch + 1) == nums_epochs:
        print(f"Epoch {epoch+1:03d}/{nums_epochs} | Loss: {current_loss:.6f} | Best: {best['best_loss']:.6f} | Patience: {patience_counter}/{patience}")

    # KÍCH HOẠT DỪNG SỚM
    if patience_counter >= patience:
        print(f"\nEARLY STOP")
        print(f"   Đã dừng tại Epoch {epoch+1} vì Loss không giảm trong {patience} epochs liên tiếp.")
        print(f"   Best Loss đạt được: {best['best_loss']:.6f}")
        break

print("\nQuá trình huấn luyện kết thúc.")
print(f"   Best Loss đạt được: {best['best_loss']:.6f} đạt tại {best['best_epoch']}")

model.eval()
with torch.no_grad():
    z_final = model.encode(data.x, edge_index=data.edge_index, edge_attr=data.edge_attr).cpu().numpy()

np.save(folder_path + 'node_embeddings.npy', z_final)

print(f"Vector Embedding cuối cùng: {z_final.shape}")
print(f"Đã lưu vào file: {folder_path + 'node_embeddings.npy'}")

# Chuyển đổi loss_history thành một pandas Series để tính toán trung bình di động
loss_series = pd.Series(loss_history)
loss_smooth = loss_series.rolling(window=20).mean()

# Lấy giá trị best loss và best epoch trực tiếp từ dictionary 'best'
best_loss_val = best['best_loss']
best_epoch_val = best['best_epoch']

plt.figure(figsize=(12, 8))

# Tạo trục x là các epoch (1-indexed)
epochs_range = range(1, len(loss_series) + 1)

# Vẽ đường Loss gốc (Mờ hơn)
plt.plot(
    epochs_range,
    loss_series,
    color='cornflowerblue',
    alpha=0.6,
    linewidth=1,
    label='Raw Loss'
)

# Vẽ đường Loss đã làm trơn (Đậm, rõ nét)
plt.plot(
    epochs_range,
    loss_smooth,
    color='darkblue',
    linewidth=2.5,
    label='Smoothed Trend'
)

plt.scatter(
    best_epoch_val,
    best_loss_val,
    color='#d62728', # Màu đỏ nổi bật
    s=100,           # Kích thước chấm
    marker='o',      # Hình ngôi sao
    zorder=5,        # Vẽ đè lên trên cùng
    label=f'Best Loss: {best_loss_val:.4f}'
)

# Thêm chú thích text ngay tại điểm đó
plt.annotate(
    f'{best_loss_val:.4f}',
    xy=(best_epoch_val, best_loss_val),
    xytext=(best_epoch_val, best_loss_val + 0.05), # Dịch text lên trên một chút
    arrowprops=dict(facecolor='black', arrowstyle='->'),
    fontsize=11,
    fontweight='bold',
    bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="black", alpha=0.8), # Khung text
    ha='center'
)

max_epoch = len(loss_series) # Sử dụng độ dài của lịch sử loss cho số epoch tối đa
ticks = np.arange(0, max_epoch + 101, 100)
plt.xticks(ticks, fontsize=10)

plt.title('Quá trình Hội tụ của Mô hình GAT-GAE', fontsize=12, fontweight='bold')
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Reconstruction Loss (BCE)', fontsize=12)
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""> GOM CỤM VỚI K-MEANS

TÌM K TỐI ƯU CHO K-MEANS
"""

node_ids = df_nodes['profile_id'].values
embeddings = np.load(folder_path + 'node_embeddings.npy')

print(f"Đã load embedding: {embeddings.shape}")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score

# CẤU HÌNH THAM SỐ
K_range = range(10, 31) # Thử từ 3 cụm đến 16 cụm
inertia_values = []
silhouette_values = []
davies_bouldin_values = []

# VÒNG LẶP TRAINING
for k in K_range:
    # n_init=10: Chạy 10 lần với điểm bắt đầu ngẫu nhiên để lấy kết quả tốt nhất
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(embeddings)

    inertia_values.append(kmeans.inertia_)
    silhouette_values.append(silhouette_score(embeddings, labels))
    davies_bouldin_values.append(davies_bouldin_score(embeddings, labels))

    print(f"K={k:02d} | Silhouette: {silhouette_values[-1]:.4f} | DB Index: {davies_bouldin_values[-1]:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# VẼ BIỂU ĐỒ TRỰC QUAN HÓA
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Biểu đồ 1: Elbow (Inertia)
# axes[0].plot(K_range, inertia_values, 'bo-', markersize=8)
# axes[0].set_title('Elbow Method (Inertia)')
# axes[0].set_xlabel('Số lượng cụm (K)')
# axes[0].set_ylabel('Inertia (Thấp là tốt)')
# axes[0].set_xticks(K_range)
# axes[0].grid(True, linestyle='--')

# Biểu đồ 2: Silhouette Score
axes[0].plot(K_range, silhouette_values, 'go-', markersize=8)
axes[0].set_title('Silhouette Score')
axes[0].set_xlabel('Số lượng cụm (K)')
axes[0].set_ylabel('Score (Cao là tốt)')
axes[0].set_xticks(K_range)
axes[0].grid(True, linestyle='--')

# Đánh dấu điểm cao nhất
max_sil_idx = np.argmax(silhouette_values)
axes[0].plot(K_range[max_sil_idx], silhouette_values[max_sil_idx], 'r*', markersize=15)

# Biểu đồ 3: Davies-Bouldin
axes[1].plot(K_range, davies_bouldin_values, 'ro-', markersize=8)
axes[1].set_title('Davies-Bouldin Index')
axes[1].set_xlabel('Số lượng cụm (K)')
axes[1].set_ylabel('Index (Thấp là tốt)')
axes[1].set_xticks(K_range)
axes[1].grid(True, linestyle='--')

# Đánh dấu điểm thấp nhất
min_db_idx = np.argmin(davies_bouldin_values)
axes[1].plot(K_range[min_db_idx], davies_bouldin_values[min_db_idx], 'b*', markersize=15)
axes[1].legend()

plt.tight_layout()
plt.show()

print("inertia_values:", inertia_values)
print("silhouette_values:", silhouette_values)
print("davies_bouldin_values:", davies_bouldin_values)

# GOM CỤM (K-MEANS) với K tối ưu
NUM_CLUSTERS = 29
kmeans = KMeans(n_clusters=NUM_CLUSTERS, random_state=42)
labels = kmeans.fit_predict(embeddings)

df_clustered = pd.DataFrame({
    'profile_id': node_ids,
    'cluster_label': labels
})

output_path = folder_path + 'kmeans_labels.csv'
df_clustered.to_csv(output_path, index=False)
print(f"Đã lưu nhãn gom cụm vào: {output_path}")

from sklearn.manifold import TSNE

# Tạo DataFrame để dễ xử lý
df_plot = pd.DataFrame(embeddings)
df_plot['node_id'] = node_ids
df_plot['cluster'] = labels # Nhãn cụm dự đoán

# VẼ BIỂU ĐỒ T-SNE (SCATTER PLOT)
# Giảm chiều 64D -> 2D
tsne = TSNE(n_components=2, perplexity=30, random_state=42, init='pca', learning_rate=200)
z_2d = tsne.fit_transform(embeddings)


plt.figure(figsize=(12, 8))
sns.scatterplot(
    x=z_2d[:,0],
    y=z_2d[:,1],
    hue=labels,
    palette='tab20',
    s=80,
    alpha=0.8,
    edgecolor='k',
    linewidth=0.5
)
plt.title('Phân bố các Node trong không gian 2D (t-SNE)', fontsize=16)
plt.xticks([])
plt.yticks([])
plt.legend(title='Clusters')
plt.show()

import pandas as pd

df = df_nodes.merge(df_clustered, on='profile_id', how='inner')

cluster_stats = df.groupby('cluster_label').agg({
    'profile_id': 'count',
    'trust_score': 'mean',
    'handle': lambda x: list(x.dropna().sample(min(len(x), 3))) # Lấy mẫu 3 tên
}).rename(columns={'profile_id': 'Size', 'trust_score': 'Avg_Trust'})

# Sắp xếp theo Trust Score để dễ nhìn (Bot thường Trust thấp)
cluster_stats = cluster_stats.sort_values(by='Avg_Trust')
cluster_stats

min_size = cluster_stats['Size'].min()
max_size = cluster_stats['Size'].max()
print(f"Kích thước cụm nhỏ nhất: {min_size}")
print(f"Kích thước cụm lớn nhất: {max_size}")

"""# PHẦN III: GÁN NHÃN DỰA TRÊN LUẬT"""

df_merged = df_nodes.merge(df_clustered, on='profile_id', how='inner')
df_merged['created_on'] = pd.to_datetime(df_merged['created_on'])

print(f"Đã merge thành công {len(df_merged)}")

# Tạo từ điển ánh xạ: Node ID -> Cluster ID
node_to_cluster = df_clustered.set_index('profile_id')['cluster_label'].to_dict()

# Lọc các cạnh "Nội bộ" (Internal Edges)
df_edges['src_cluster'] = df_edges['source'].map(node_to_cluster)
df_edges['dst_cluster'] = df_edges['target'].map(node_to_cluster)
internal_edges = df_edges[df_edges['src_cluster'] == df_edges['dst_cluster']].copy()

print(f"Đã lọc thành công {len(internal_edges)}")

similarity_types = ['SAME_AVATAR', 'SIM_BIO', 'CLOSE_CREATION_TIME', 'FUZZY_HANDLE']
social_types = ['FOLLOW', 'UPVOTE', 'COMMENT', 'COLLECT']


def calculate_cluster_stats(cluster_id):
    nodes_in_cluster = df_merged[df_merged['cluster_label'] == cluster_id]
    edges_in_cluster = internal_edges[internal_edges['src_cluster'] == cluster_id]

    total_edges = len(edges_in_cluster)
    if total_edges == 0:
        total_edges = 1 # Tránh chia cho 0

    avg_trust = nodes_in_cluster['trust_score'].mean()

    # Std Creation Hours (Độ lệch chuẩn thời gian tạo)
    if len(nodes_in_cluster) > 1:
        std_seconds = nodes_in_cluster['created_on'].std().total_seconds()
        std_hours = std_seconds / 3600
    else:
        std_hours = 0

    # Tính tỷ lệ các loại cạnh
    type_counts = edges_in_cluster['type'].value_counts()
    def get_pct(type_list):
        count = type_counts[type_counts.index.isin(type_list)].sum()
        return count / total_edges

    # Định nghĩa các nhóm loại cạnh
    co_owner_types = ['CO-OWNER']
    fuzzy_handle_types = ['FUZZY_HANDLE']

    stats = {
        'cluster_id': cluster_id,
        'size': len(nodes_in_cluster),
        'avg_trust': avg_trust,
        'std_creation_hours': std_hours,
        'pct_co_owner': get_pct(co_owner_types),
        'pct_fuzzy_handle': get_pct(fuzzy_handle_types),
        'pct_similarity': get_pct(similarity_types),
        'pct_social': get_pct(social_types)
    }
    return stats

num_cluster = len(df_clustered['cluster_label'].unique().tolist())
print(f"Đang kiểm tra {num_cluster} cụm")

df_stats = pd.DataFrame([calculate_cluster_stats(k) for k in range(num_cluster)])
print(f"Đã tính toán thành công {len(df_stats)}")

"""> Thống kê các cụm"""

df_stats

import matplotlib.pyplot as plt

# Cài đặt dữ liệu
edges_composition = df_stats.set_index('cluster_id')[['pct_co_owner', 'pct_similarity', 'pct_social']]
edges_composition.columns = ['Co-Owner', 'Similarity', 'Social']

# Sắp xếp theo kích thước cụm để dễ nhìn (Cụm to lên đầu)
edges_composition['size'] = df_stats.set_index('cluster_id')['size']
edges_composition = edges_composition.sort_values('size', ascending=False).drop(columns=['size'])

# Vẽ biểu đồ
ax = edges_composition.plot(kind='bar', stacked=True, figsize=(14, 7), width=0.8,
                            color=['#e74c3c', '#9b59b6', '#2ecc71'])

plt.title('Giải phẫu Thành phần edges của các (Sắp xếp giảm dần theo Kích thước cụm)', fontsize=16, weight='bold', pad=15)
plt.xlabel('ID Cụm', fontsize=13)
plt.ylabel('Tỷ lệ % Thành phần', fontsize=13)

# Chuyển trục Y sang %
import matplotlib.ticker as mtick
ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0))

plt.legend(title='Loại Liên kết', bbox_to_anchor=(1.01, 1), loc='upper left')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

PCT_CO_OWNER_THRESHOLD = 0.1
PCT_FUZZY_HANDLE_THRESHOLD = 0.50
PCT_SIMILARITY_THRESHOLD = 0.60
STD_CREATION_HOURS_THRESHOLD = 0.5
PCT_SOCIAL_THRESHOLD = 0.20
AVG_TRUST_THRESHOLD = 8
FALLBACK_LOW_TRUST_THRESHOLD = 5 # New threshold for fallback rule

def calculate_sybil_risk_score(stats):
    """
    Hệ thống chấm điểm rủi ro cộng dồn (Additive Risk Scoring)
    Điểm rủi ro (Risk Score) dao động từ 0 đến 100.
    """
    score = 0
    reasons = []

    # 1. Tiêu chí Đồng sở hữu (Co-owner) - Rất nghiêm trọng
    if stats['pct_co_owner'] > PCT_CO_OWNER_THRESHOLD:
        score += 50
        reasons.append(f"Co-owner ({stats['pct_co_owner']:.1%}) [+50]")

    # 2. Tiêu chí Tương đồng Siêu dữ liệu (Similarity) - CHIA BẬC
    if stats['size'] > 2 and stats['pct_similarity'] >= PCT_SIMILARITY_THRESHOLD:
        score += 30
        reasons.append(f"High Similarity ({stats['pct_similarity']:.1%}) [+30]")

    # 3. Tiêu chí Khởi tạo hàng loạt (Batch Creation)
    # CHỈ ÁP DỤNG cho các cụm có nhiều hơn 1 tài khoản
    if stats['size'] > 1 and stats['std_creation_hours'] < STD_CREATION_HOURS_THRESHOLD:
        score += 15
        reasons.append(f"Batch Creation (< 2h std) [+15]")

    # 4. Tiêu chí Cú pháp tên (Fuzzy Handle)
    if stats['pct_fuzzy_handle'] >= PCT_FUZZY_HANDLE_THRESHOLD:
        score += 15
        reasons.append(f"Fuzzy Handle ({stats['pct_fuzzy_handle']:.1%}) [+15]")

    # 5. Tiêu chí Tương tác Xã hội thấp (Low Social)
    if stats['pct_social'] <= PCT_SOCIAL_THRESHOLD:
        score += 10
        reasons.append(f"Low Social ({stats['pct_social']:.1%}) [+10]")

    # 6. Tiêu chí Độ tin cậy (Trust Score)
    if stats['avg_trust'] <= FALLBACK_LOW_TRUST_THRESHOLD:
        score += 20
        reasons.append(f"Extremely Low Trust ({stats['avg_trust']:.2f}) [+20]")
    elif stats['avg_trust'] <= AVG_TRUST_THRESHOLD:
        score += 10
        reasons.append(f"Low Trust ({stats['avg_trust']:.2f}) [+10]")

    # Chuẩn hóa điểm số tối đa là 100
    risk_score = min(score, 100)

    # Phân lớp mờ (Fuzzy Labeling - 4 Classes)
    if risk_score < 20:
        label = "0_BENIGN"
    elif risk_score <= 50:
        label = "1_LOW_RISK"
    elif risk_score < 80:
        label = "2_HIGH_RISK"
    else:
        label = "3_MALICIOUS"

    if not reasons:
        reasons.append("Organic behavior")

    return risk_score, label, " | ".join(reasons)

# TỔNG HỢP KẾT QUẢ VỚI FUZZY LABELING
results = []
for k in range(num_cluster):
    stats = df_stats.iloc[k].to_dict()

    # Áp dụng cơ chế chấm điểm
    risk_score, label, reason = calculate_sybil_risk_score(stats)

    # Lưu kết quả
    stats['risk_score'] = risk_score
    stats['label'] = label
    stats['reason'] = reason
    results.append(stats)

df_results = pd.DataFrame(results)
df_results['cluster_id'] = df_results['cluster_id'].astype(int)
df_results['size'] = df_results['size'].astype(int)

print(f"Đã chấm điểm rủi ro cho {len(results)} cụm")
df_results[['cluster_id', 'size', 'risk_score', 'label', 'reason']]

df_profile_with_sybil_labels = df_merged.merge(df_results[['cluster_id', 'label',  'risk_score', 'reason']], left_on='cluster_label', right_on='cluster_id', how='left')
df_final_labels = df_profile_with_sybil_labels[['profile_id', 'label', 'risk_score', 'reason']]

print(f"Đã merge thành công {len(df_final_labels)}")

output_file_path = folder_path + 'rule_based_scoring_labels.csv'
df_final_labels.to_csv(output_file_path, index=False)
print(f"Đã lưu file profile_id và nhãn Sybil/Non-Sybil vào: {output_file_path}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


label_order = ['0_BENIGN', '1_LOW_RISK', '2_HIGH_RISK', '3_MALICIOUS']
danger_palette = ['#2ecc71', '#f1c40f', '#e67e22', '#c0392b']

sybil_counts = df_final_labels['label'].value_counts()
sybil_counts_ordered = sybil_counts.reindex(label_order, fill_value=0)

plt.figure(figsize=(8, 6))
ax = sns.barplot(x=sybil_counts_ordered.index,
                 y=sybil_counts_ordered.values,
                 palette=danger_palette,
                 order=label_order)

max_val = max(sybil_counts_ordered.values)

for i, v in enumerate(sybil_counts_ordered.values):
    ax.text(i, v + (max_val * 0.02),   # Tọa độ Y nhích lên 2% so với đỉnh cột
            str(int(v)),               # Ép kiểu int để số hiển thị đẹp không có dấu phẩy
            ha='center',
            va='bottom',
            fontsize=12,
            fontweight='bold',         # In đậm số liệu cho rõ ràng
            color='#333333')

plt.title('Phân phối nhãn', fontsize=15, fontweight='bold', pad=15)
plt.xlabel('', fontsize=4)
plt.ylabel('Số lượng tài khoản', fontsize=12)
plt.xticks(fontsize=11)
plt.yticks(fontsize=11)

plt.ylim(0, max_val * 1.15)
plt.tight_layout()
plt.show()

total_labels = sybil_counts.sum()
pct_beign = (sybil_counts['0_BENIGN'] / total_labels) * 100
pct_low_risk = (sybil_counts['1_LOW_RISK'] / total_labels) * 100
pct_high_risk = (sybil_counts['2_HIGH_RISK'] / total_labels) * 100
pct_malicious = (sybil_counts['3_MALICIOUS'] / total_labels) * 100

print(f"Tỷ lệ BENIGN: {pct_beign:.2f}%")
print(f"Tỷ lệ LOW_RISK: {pct_low_risk:.2f}%")
print(f"Tỷ lệ HIGH_RISK: {pct_high_risk:.2f}%")
print(f"Tỷ lệ MALICIOUS: {pct_malicious:.2f}%")

"""> Xác nhận dữ liệu gán nhãn"""

import plotly.graph_objects as go
import networkx as nx

def visualize_cluster_plotly(cluster_id, G, df_labels):
    cluster_col = 'cluster_label' if 'cluster_label' in df_labels.columns else 'cluster_id'
    target_nodes = [str(x).strip().lower() for x in df_labels[df_labels[cluster_col] == cluster_id]['profile_id']]
    sub_G = G.subgraph([n for n in target_nodes if G.has_node(n)])

    if len(sub_G.nodes()) == 0:
        print("   ❌ Lỗi: Không tìm thấy node.")
        return

    print(f"Dữ liệu vẽ: {len(sub_G.nodes())} nodes và {len(sub_G.edges())} edges.")

    try:
        # Lựa chọn 1: Kamada Kawai (Giữ khoảng cách hình học bám sát cấu trúc liên kết)
        pos = nx.kamada_kawai_layout(sub_G)
    except:
        # Lựa chọn 2: Fallback về Spring Layout (Nếu đồ thị có cụm bị đứt gãy/cô lập)
        k_value = 0.3 if len(sub_G.nodes()) < 20 else 0.15
        pos = nx.spring_layout(sub_G, seed=42, k=k_value, iterations=600)

    # Khởi tạo danh sách các đường nối (Edges) và Mũi tên/Nhãn (Annotations)
    edge_traces = []
    annotations = []

    edge_colors = {
        'Co-Owner': 'rgba(220, 38, 38, 0.8)',    # Tăng độ đậm để dễ đọc chữ
        'Similarity': 'rgba(139, 92, 246, 0.8)',
        'Follow': 'rgba(59, 130, 246, 0.8)',
        'Interact': 'rgba(6, 182, 212, 0.8)'
    }

    for u, v, data in sub_G.edges(data=True):
        x0, y0 = pos[u]
        x1, y1 = pos[v]
        layer = data.get('layer', 'Interact')

        color = edge_colors.get(layer, 'rgba(136, 136, 136, 0.8)')
        width = 3 if layer == 'Co-Owner' else (2 if layer == 'Similarity' else 1)
        dash = 'dash' if layer == 'Similarity' else 'solid'
        hover_info = f"Liên kết: {layer}<br>Lý do: {data.get('reason','')}" if layer == 'Similarity' else f"Liên kết: {layer}"

        # Vẽ đoạn thẳng nối giữa 2 Node
        edge_traces.append(go.Scatter(
            x=[x0, x1, None], y=[y0, y1, None],
            line=dict(width=width, color=color, dash=dash),
            hoverinfo='text',
            text=hover_info,
            mode='lines',
            showlegend=False
        ))

        # mid_x = (x0 + x1) / 2
        # mid_y = (y0 + y1) / 2
        # annotations.append(
        #     dict(
        #         x=mid_x, y=mid_y,
        #         text=layer,                 # Hiển thị tên Layer (Co-Owner, Follow...)
        #         showarrow=False,            # Đây là nhãn chữ, không phải mũi tên
        #         font=dict(size=9, color=color.replace('0.8', '1.0')), # Chữ cùng màu với viền nhưng đậm hơn
        #         bgcolor='rgba(255, 255, 255, 0.85)', # Nền trắng trong suốt để che đi phần nét gạch đè lên chữ
        #         bordercolor=color,
        #         borderwidth=0.5,
        #         borderpad=2
        #     )
        # )

        # TẠO MŨI TÊN CÓ HƯỚNG CHO FOLLOW VÀ INTERACT
        if layer in ['Follow', 'Interact']:
            annotations.append(
                dict(
                    ax=x0, ay=y0, axref='x', ayref='y',
                    x=x1, y=y1, xref='x', yref='y',
                    showarrow=True,
                    arrowhead=2,
                    arrowsize=1.5,
                    arrowwidth=width,
                    arrowcolor=color,
                    standoff=16
                )
            )

    # Khởi tạo danh sách các điểm (Nodes)
    node_x = []
    node_y = []
    node_colors = []
    node_hover_texts = []
    node_display_texts = []

    # Gom màu theo Ví
    unique_wallets = list(set([sub_G.nodes[n].get('owned_by', 'N/A') for n in sub_G.nodes()]))
    colors = ['#3b82f6', '#10b981', '#f59e0b', '#f97316', '#ec4899', '#14b8a6', '#6366f1', '#eab308', '#ef4444']
    wallet_map = {w: colors[i % len(colors)] for i, w in enumerate(unique_wallets)}

    for node in sub_G.nodes():
        x, y = pos[node]
        node_x.append(x)
        node_y.append(y)

        attrs = sub_G.nodes[node]
        handle = attrs.get('handle', str(node))
        wallet = attrs.get('owned_by', 'N/A')
        trust = attrs.get('trust_score', 0.0)
        score = attrs.get('risk_score', 0.0)
        label = attrs.get('label', 'N/A')
        reason = attrs.get('reason', 'N/A')

        node_colors.append(wallet_map.get(wallet, '#333'))

        display_handle = handle[:10] + ".." if len(handle) > 12 else handle
        node_display_texts.append(display_handle)

        hover_text = f"""
<b>Handle:</b> {handle}
<br>
<b>Owned By:</b> {wallet}
<br>
<b>Trust Score:</b> {trust:.2f}
<br>
<b>Risk Score:</b> {score:.2f}
<br>
<b>Label:</b> {label}
<br>
<b>Reason:</b> {reason}
          """
        node_hover_texts.append(hover_text)

    # Vẽ toàn bộ Node cùng 1 lúc
    node_trace = go.Scatter(
        x=node_x, y=node_y,
        mode='markers+text',
        hoverinfo='text',
        hovertext=node_hover_texts,
        text=node_display_texts,
        textposition="top center",
        textfont=dict(
            size=12,
            color='#334155',
            weight='bold'
        ),
        marker=dict(
            showscale=False,
            color=node_colors,
            size=28,
            line_width=2,
            line_color='#1e293b'
        )
    )

    # Đóng gói và Hiển thị
    fig = go.Figure(data=edge_traces + [node_trace],
                 layout=go.Layout(
                    title=dict(
                        text=f'<b>Cấu trúc Tương tác Cụm Rủi ro [{cluster_id}]</b>',
                        font=dict(size=22)
                    ),
                    width=1000,
                    height=800,
                    showlegend=False,
                    hovermode='closest',
                    margin=dict(b=20, l=20, r=20, t=60),
                    plot_bgcolor='#f8fafc',
                    paper_bgcolor='#ffffff',
                    annotations=annotations,
                    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False, constrain='domain'),
                    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False, scaleanchor="x", scaleratio=1))
                 )

    fig.update_layout(dragmode="pan")
    fig.show()

import pandas as pd
import networkx as nx
import plotly.graph_objects as go

def build_multidigraph(df_nodes, df_edges, df_final_labels):
    G = nx.MultiDiGraph()

    df_nodes = df_nodes.merge(df_final_labels[['profile_id', 'label', 'risk_score', 'reason']], on='profile_id', how='left')

    for _, row in df_nodes.iterrows():
        raw_id = str(row['profile_id']).strip().lower()
        G.add_node(
            raw_id,
            handle=str(row.get('handle', raw_id)),
            owned_by=str(row.get('owned_by', 'N/A')).strip().lower(),
            created_on=str(row.get('created_on', 'N/A')),
            trust_score=row.get('trust_score', 0.0),
            risk_score=row.get('risk_score', 0.0),
            label=row.get('label', 'N/A'),
            reason=row.get('reason', 'N/A')
        )

    for _, row in df_edges.iterrows():
        u = str(row['source']).strip().lower()
        v = str(row['target']).strip().lower()
        layer = str(row.get('layer', 'Interact'))
        e_type = str(row.get('type', 'N/A'))

        # Kiểm tra xem cả 2 node có tồn tại trong đồ thị không
        if G.has_node(u) and G.has_node(v):
            # Thêm thẳng cạnh vào đồ thị (MultiDiGraph tự động cấp key phân biệt cho các cạnh trùng)
            G.add_edge(u, v, layer=layer, e_type=e_type)

    print(f"Hoàn tất: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges (bao gồm các cạnh song song).")
    return G

# Khởi tạo đồ thị
G_clean = build_multidigraph(df_nodes, df_edges, df_final_labels)

visualize_cluster_plotly(0, G_clean, df_clustered)

visualize_cluster_plotly(25, G_clean, df_clustered)

visualize_cluster_plotly(15, G_clean, df_clustered)

visualize_cluster_plotly(8, G_clean, df_clustered)



import pandas as pd
from IPython.display import display

def inspect_cluster_raw_data(cluster_id, df_labels, df_nodes, df_results, top_n=10):
    """
    Hàm phân tích dữ liệu thô phục vụ xác thực thủ công (Human-in-the-loop).
    Đánh giá dựa trên 3 tiêu chí: Tài chính (Co-Owner), Thời gian (Temporal) và Nội dung (Automation).
    """
    # Lấy profile_id từ df_clustered, nơi chứa ánh xạ profile_id với cluster_label
    # df_clustered là biến toàn cục chứa thông tin này
    nodes_in_cluster = df_clustered[df_clustered['cluster_label'] == cluster_id]['profile_id'].tolist()
    raw_data = df_nodes[df_nodes['profile_id'].isin(nodes_in_cluster)].copy()

    cols_to_show = ['profile_id', 'handle', 'bio', 'owned_by', 'created_on']
    actual_cols = [col for col in cols_to_show if col in raw_data.columns]

    if 'created_on' in raw_data.columns:
        raw_data['created_on'] = pd.to_datetime(raw_data['created_on'])
        raw_data = raw_data.sort_values('created_on')

    total_accounts = len(raw_data)
    print(f"\nBÁO CÁO PHÂN TÍCH CỤM [{cluster_id}]")
    print(f"Tổng số tài khoản: {total_accounts} | Hiển thị mẫu: {min(top_n, total_accounts)}")
    print("-" * 80)

    display(raw_data[actual_cols].head(top_n))

    cluster_stats_row = df_results[df_results['cluster_id'] == cluster_id].iloc[0]

    # Khía cạnh 1: Đồng sở hữu ví
    print("-" * 80)
    print("[1] Phân tích Tài chính (Đồng sở hữu ví):")
    if 'owned_by' in actual_cols:
        pct_co_owner_graph = cluster_stats_row['pct_co_owner']
        wallet_counts = raw_data['owned_by'].value_counts()
        shared_accounts = wallet_counts[wallet_counts > 1].sum()
        unique_wallets = len(wallet_counts)

        top_wallet = wallet_counts.index[0] if not wallet_counts.empty else "N/A"
        top_wallet_count = wallet_counts.iloc[0] if not wallet_counts.empty else 0

        if shared_accounts == 0:
            print(f"    -> Bình thường: 0% tài khoản trùng ví ({total_accounts} tài khoản / {unique_wallets} ví độc lập).")
        elif pct_co_owner_graph > 0.10:
            print(f"    -> Cảnh báo rủi ro (Co-owner): Tỷ lệ đồ thị đạt {pct_co_owner_graph:.1%} (>10%).")
            print(f"       - Xác minh thực tế: {shared_accounts}/{total_accounts} tài khoản sử dụng chung ví.")
            print(f"       - Ví trọng tâm: {top_wallet} (sở hữu {top_wallet_count} tài khoản).")
        else:
            print(f"    -> Bình thường: Tỷ lệ trùng ví thấp ({shared_accounts}/{total_accounts} tài khoản).")

    # Khía cạnh 2: Thời gian tạo tài khoản
    print("\n[2] Phân tích Thời gian (Khởi tạo hàng loạt):")
    if 'created_on' in actual_cols:
        time_span = raw_data['created_on'].max() - raw_data['created_on'].min()
        std_hours = cluster_stats_row['std_creation_hours']

        print(f"    -> Khoảng thời gian tạo toàn bộ {total_accounts} tài khoản: {time_span}")
        if std_hours < 0.5 and total_accounts > 1:
            print(f"    -> Cảnh báo rủi ro: Độ lệch chuẩn thời gian thấp ({std_hours:.2f}h). Khả năng tạo tự động bằng script.")
        else:
            print(f"    -> Bình thường: Phân bố thời gian khởi tạo hợp lý (Độ lệch chuẩn: {std_hours:.2f}h).")

    # Khía cạnh 3: Nội dung hồ sơ
    print("\n[3] Phân tích Nội dung (Khuôn mẫu tự động):")
    pct_sim = cluster_stats_row['pct_similarity']
    pct_fuzzy = cluster_stats_row['pct_fuzzy_handle']

    if pct_sim >= 0.60:
        print(f"    -> Cảnh báo rủi ro: Tỷ lệ sao chép hồ sơ (Similarity) cao, đạt {pct_sim:.1%}.")
    else:
        print(f"    -> Bình thường: Hồ sơ đa dạng, tỷ lệ trùng lặp thấp ({pct_sim:.1%}).")

    if pct_fuzzy >= 0.50:
        print(f"    -> Cảnh báo rủi ro: Tên tài khoản (Fuzzy Handle) có dấu hiệu sinh tự động, đạt {pct_fuzzy:.1%}.")
    else:
        print(f"    -> Bình thường: Cú pháp tên tài khoản không có dấu hiệu sinh tự động ({pct_fuzzy:.1%}).")
    print("=" * 80)


# --- TRÍCH XUẤT MẪU PHÂN TẦNG ---
target_labels = ['0_BENIGN', '1_LOW_RISK', '2_HIGH_RISK', '3_MALICIOUS']
sampled_clusters = {}

print("TIẾN HÀNH TRÍCH XUẤT MẪU PHÂN TẦNG (STRATIFIED SAMPLING)")
print("=" * 80)

for label in target_labels:
    subset = df_results[df_results['label'] == label]
    if len(subset) > 0:
        rep = subset.sort_values(by='size', ascending=False)
        c_id = int(rep['cluster_id'].iloc[0])
        sampled_clusters[label] = c_id

        print(f"Lớp [{label}]: Cụm đại diện {c_id} (Kích thước: {int(rep['size'].iloc[0])} nodes | Điểm rủi ro: {int(rep['risk_score'].iloc[0])})")
        print(f"Nguyên nhân gán nhãn: {rep['reason'].iloc[0]}\n")

# --- XUẤT BÁO CÁO ---
for label, c_id in sampled_clusters.items():
    df_labels = df_results.copy()
    inspect_cluster_raw_data(c_id, df_labels, df_nodes, df_results, top_n=8)



"""# Huấn luyện mô hình có giám sát"""

from google.colab import drive

drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/LuanVan/data/raw_first-week-of-dec-2025/"

!pip install torch_geometric

import torch

data = torch.load(folder_path + 'graph_data.pt', weights_only=False)
print(data)

import pandas as pd

df_labels = pd.read_csv(folder_path + 'rule_based_scoring_labels.csv')
df_edges = pd.read_csv(folder_path + 'edges_weighted.csv')

# Chuyển nhãn (Sybil=1, Non-Sybil=0) thành Tensor
y_mapping = {
  '0_BENIGN': 0,
  '1_LOW_RISK': 1,
  '2_HIGH_RISK': 2,
  '3_MALICIOUS': 3
}

y = torch.tensor(df_labels['label'].map(y_mapping).values, dtype=torch.long)

data.y = y
print("Đã thêm nhãn 'y' vào đối tượng data thành công.")

data_save_path = folder_path + 'processed_sybil_data.pt'
torch.save(data, data_save_path)

print(f"Đã lưu thành công tại: {data_save_path}")

# Lấy node features từ đối tượng data đã tải ở cell LMVHNqNpNEfr
x = data.x
labels = data.y.numpy()
indices = range(data.num_nodes)

"""> Chia dữ liệu thành Train/Test/Val"""

from sklearn.model_selection import train_test_split

# Stratified Split (Chia theo tỷ lệ nhãn)
train_idx, temp_idx = train_test_split(
    indices,
    test_size=0.4,
    stratify=labels,
    random_state=42
)

val_idx, test_idx = train_test_split(
    temp_idx,
    test_size=0.5,
    stratify=labels[temp_idx],
    random_state=42
)

print(f"Train Size: {len(train_idx)} (60%)")
print(f"Val Size:   {len(val_idx)} (20%)")
print(f"Test Size:  {len(test_idx)} (20%)")

# Tạo Mask
train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
val_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)

train_mask[train_idx] = True
val_mask[val_idx] = True
test_mask[test_idx] = True

data.train_mask = train_mask
data.val_mask = val_mask
data.test_mask = test_mask

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

import torch
import torch.nn as nn

# 1. Trích xuất nhãn chỉ thuộc tập Train (Đảm bảo tính khách quan)
y_train = data.y[train_mask]

# 2. Tự động đếm số lượng node của TỪNG LỚP (Sẽ sinh ra mảng 4 phần tử cho lớp 0,1,2,3)
class_counts = torch.bincount(y_train)
total_train = len(y_train)
num_classes = len(class_counts) # Ở đây sẽ tự động nhận diện là 4 lớp

print(f"Số lượng mẫu mỗi lớp trong tập Train: {class_counts.tolist()}")

# 3. Tính Class Weights theo công thức chuẩn cân bằng (Balanced Heuristic)
# Trọng số = Tổng số mẫu / (Số lượng lớp * Số mẫu của lớp đó)
# Lưu ý: Cộng thêm 1e-8 để tránh lỗi ZeroDivisionError nếu lỡ có lớp nào bị rỗng
class_weights = total_train / (num_classes * class_counts.float() + 1e-8)

print(f"Class Weights (Calculated on Train set):")
print(f"   - Lớp 0 (BENIGN):      {class_weights[0]:.4f}")
print(f"   - Lớp 1 (LOW_RISK):    {class_weights[1]:.4f}")
print(f"   - Lớp 2 (HIGH_RISK):   {class_weights[2]:.4f}")
print(f"   - Lớp 3 (MALICIOUS):   {class_weights[3]:.4f}")

# 4. Đưa trọng số lên GPU (CỰC KỲ QUAN TRỌNG để tránh lỗi mismatch device)
# Đảm bảo bạn đã khai báo biến 'device' trước đó
class_weights = class_weights.to(device)

# 5. Khởi tạo Loss & Optimizer
# Truyền class_weights vào CrossEntropyLoss để phạt nặng nếu đoán sai lớp thiểu số (BENIGN)
criterion = nn.CrossEntropyLoss(weight=class_weights)

"""> Huấn luyện mô hình

## GNNs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import torch
import torch.nn.functional as F
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix
)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hàm cố định hạt giống ngẫu nhiên để đảm bảo tính tái lập (Reproducibility)
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

def run_repeated_gnn_experiments(
    model_class, model_kwargs, data, device, class_weights,
    n_runs=5, epochs=1000, patience=100, lr=0.001, weight_decay=5e-4,
    class_names=['0_BENIGN', '1_LOW_RISK', '2_HIGH_RISK', '3_MALICIOUS'],
    save_path='best_gnn_model.pth' # <--- THÊM THAM SỐ LƯU ĐƯỜNG DẪN
):
    seeds = [42, 123, 999, 2024, 777, 888, 111, 222, 333, 444][:n_runs]

    all_metrics = []

    # Biến theo dõi Nhà vô địch toàn cục (Global Best)
    global_best_test_f1 = 0.0

    print("="*80)
    print(f"🚀 BẮT ĐẦU THỰC NGHIỆM: {model_class.__name__} ({n_runs} LẦN CHẠY)")
    print(f"💾 Mô hình tốt nhất sẽ được lưu tại: {save_path}")
    print("="*80)

    for i, seed in enumerate(seeds):
        set_seed(seed)

        model = model_class(**model_kwargs).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
        criterion = torch.nn.CrossEntropyLoss(weight=class_weights.to(device))

        best_val_f1 = 0
        best_epoch = 0
        patience_counter = 0
        best_weights = None
        history = {'train_loss': [], 'val_loss': [], 'val_f1': []}

        print(f"\n" + "-"*60)
        print(f"🔄 Đang chạy Lần {i+1}/{n_runs} (Seed: {seed})")
        print("-"*60)

        for epoch in range(epochs):
            model.train()
            optimizer.zero_grad()
            out = model(data.x, data.edge_index, data.edge_attr)
            train_loss = criterion(out[data.train_mask], data.y[data.train_mask])
            train_loss.backward()
            optimizer.step()

            model.eval()
            with torch.no_grad():
                out_val = model(data.x, data.edge_index, data.edge_attr)
                val_loss = criterion(out_val[data.val_mask], data.y[data.val_mask]).item()
                preds_val = out_val.argmax(dim=1)

                y_true_val = data.y[data.val_mask].cpu().numpy()
                y_pred_val = preds_val[data.val_mask].cpu().numpy()
                val_f1 = f1_score(y_true_val, y_pred_val, average='macro', zero_division=0)

            history['train_loss'].append(train_loss.item())
            history['val_loss'].append(val_loss)
            history['val_f1'].append(val_f1)

            # Early Stopping
            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_epoch = epoch + 1
                best_weights = {k: v.cpu() for k, v in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1

            if patience_counter >= patience:
                break

        # 3. Đánh giá trên tập Test bằng Trọng số tốt nhất
        model.load_state_dict({k: v.to(device) for k, v in best_weights.items()})
        model.eval()
        with torch.no_grad():
            logits = model(data.x, data.edge_index, data.edge_attr)
            test_loss = criterion(logits[data.test_mask], data.y[data.test_mask]).item()
            preds = logits.argmax(dim=1)

        y_true = data.y[data.test_mask].cpu().numpy()
        y_pred = preds[data.test_mask].cpu().numpy()

        acc = accuracy_score(y_true, y_pred)
        precision = precision_score(y_true, y_pred, average='macro', zero_division=0)
        recall = recall_score(y_true, y_pred, average='macro', zero_division=0)
        f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)
        cm = confusion_matrix(y_true, y_pred)

        all_metrics.append({
            "Run": i + 1,
            "Test Loss": test_loss,
            "Accuracy": acc,
            "Macro Precision": precision,
            "Macro Recall": recall,
            "Macro F1-Score": f1,
            "Best Epoch": best_epoch
        })

        print(f"✅ Hoàn tất! Dừng tại Epoch: {best_epoch} | Test F1: {f1:.4f}")

        if f1 > global_best_test_f1:
            global_best_test_f1 = f1
            torch.save(model.state_dict(), save_path)
            print(f"  --> 🏆 Đã lưu Kỷ lục mới! (F1: {f1:.4f}) vào {save_path}")

        # ==========================================
        # 🌟 VẼ BIỂU ĐỒ CHI TIẾT CHO LẦN CHẠY HIỆN TẠI
        # ==========================================
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))

        # Biểu đồ 1: Loss Curve
        axes[0].plot(history['train_loss'], label='Train Loss', color='blue')
        axes[0].plot(history['val_loss'], label='Val Loss', color='red')
        axes[0].set_title(f'Run {i+1}: Loss Curve', fontweight='bold')
        axes[0].set_xlabel('Epochs')
        axes[0].set_ylabel('Loss')
        axes[0].legend()
        axes[0].grid(alpha=0.3)

        # Biểu đồ 2: Validation F1-Score
        axes[1].plot(history['val_f1'], label='Val F1-Score', color='green', linewidth=2)
        axes[1].axvline(best_epoch - 1, color='orange', linestyle='--', label=f'Best Epoch ({best_epoch})')
        axes[1].set_title(f'Run {i+1}: Validation F1-Score', fontweight='bold')
        axes[1].set_xlabel('Epochs')
        axes[1].set_ylabel('Macro F1-Score')
        axes[1].legend()
        axes[1].grid(alpha=0.3)

        # Biểu đồ 3: Confusion Matrix
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                    xticklabels=class_names, yticklabels=class_names,
                    annot_kws={"size": 11, "weight": "bold"}, ax=axes[2])
        axes[2].set_title(f'Run {i+1}: Confusion Matrix', fontweight='bold')
        axes[2].set_ylabel('Nhãn Thực tế')
        axes[2].set_xlabel('Nhãn Dự đoán')
        axes[2].tick_params(axis='x', rotation=45)

        plt.tight_layout()
        plt.show()

    # ==========================================
    # TỔNG HỢP VÀ IN BÁO CÁO TOÀN CỤC (METRICS)
    # ==========================================
    df_metrics = pd.DataFrame(all_metrics)

    # Tính Mean và Std
    mean_metrics = df_metrics.mean().to_dict()
    std_metrics = df_metrics.std().to_dict()

    print("\n" + "="*80)
    print("📊 BẢNG KẾT QUẢ CHI TIẾT CHO TỪNG LẦN CHẠY")
    print("="*80)
    display(df_metrics.round(4))

    print("\n" + "="*80)
    print("🏆 KẾT QUẢ TRUNG BÌNH CỦA N LẦN CHẠY")
    print("="*80)
    for col in ["Test Loss", "Accuracy", "Macro Precision", "Macro Recall", "Macro F1-Score"]:
        print(f"{col:<20}: {mean_metrics[col]:.4f}")

    return df_metrics, mean_metrics, std_metrics

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 1. GAT CLASSIFIER (Graph Attention Network)
# ==========================================
class GATClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # --- LAYER 1 ---
        self.conv1 = GATConv(in_channels, 32, heads=4, dropout=0.3, edge_dim=1)

        # --- LAYER 2 ---
        self.conv2 = GATConv(32 * 4, embedding_dim, heads=1, concat=False, dropout=0.3, edge_dim=1)

        # --- CLASSIFICATION HEAD ---
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Trích xuất đặc trưng (Embedding)
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        # Phân loại (Classification)
        out = self.classifier(x)
        return out


# Xác định class model và tham số khởi tạo
kwargs_gat = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}
path_gat = folder_path + 'best_gat_model.pth'

# Gọi thực nghiệm 5 lần chạy
df_results, mean_res, std_res = run_repeated_gnn_experiments(
    model_class=GATClassifier,    # Truyền TÊN class (không gọi hàm)
    model_kwargs=kwargs_gat,    # Truyền tham số khởi tạo
    data=data,
    device=device,
    class_weights=class_weights,  # Tensor class_weights đã tính trước đó
    n_runs=5,
    epochs=1000,
    patience=100,
    lr=0.001,
    weight_decay=5e-4,
    save_path=path_gat
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv


# ==========================================
# 2. GCN CLASSIFIER (Graph Convolutional Network)
# ==========================================
class GCNClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # GCN không có heads hay edge_dim
        self.conv1 = GCNConv(in_channels, 32)
        self.conv2 = GCNConv(32, embedding_dim)
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Biến đổi edge_attr từ 2D sang 1D cho GCN
        edge_weight = edge_attr.squeeze() if edge_attr is not None else None

        x = self.conv1(x, edge_index, edge_weight=edge_weight)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_weight=edge_weight)

        out = self.classifier(x)
        return out


# Xác định class model và tham số khởi tạo
kwargs_gcn = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_gcn = folder_path + 'best_gcn_model.pth'

# Gọi thực nghiệm 5 lần chạy
df_results, mean_res, std_res = run_repeated_gnn_experiments(
    model_class=GCNClassifier,    # Truyền TÊN class (không gọi hàm)
    model_kwargs=kwargs_gcn,    # Truyền tham số khởi tạo
    data=data,
    device=device,
    class_weights=class_weights,  # Tensor class_weights đã tính trước đó
    n_runs=5,
    epochs=1000,
    patience=100,
    lr=0.001,
    weight_decay=5e-4,
    save_path=path_gcn
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 3. GINE CLASSIFIER (Graph Isomorphism Network w/ Edges)
# ==========================================
class GINEClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # Layer 1 MLP
        mlp1 = nn.Sequential(
            nn.Linear(in_channels, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU()
        )
        self.conv1 = GINEConv(nn=mlp1, train_eps=True, edge_dim=1)

        # Layer 2 MLP
        mlp2 = nn.Sequential(
            nn.Linear(128, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, embedding_dim)
        )
        self.conv2 = GINEConv(nn=mlp2, train_eps=True, edge_dim=1)

        # Classification Head
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Ép kiểu ma trận 2D và float cho edge_attr của GINE
        if edge_attr is not None:
            if edge_attr.dim() == 1:
                edge_attr = edge_attr.view(-1, 1)
            edge_attr = edge_attr.float()

        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.dropout(x, p=0.3, training=self.training)
        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


# Xác định class model và tham số khởi tạo
kwargs_gine = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_gine = folder_path + 'best_gine_model.pth'

# Gọi thực nghiệm 5 lần chạy
df_results, mean_res, std_res = run_repeated_gnn_experiments(
    model_class=GINEClassifier,    # Truyền TÊN class (không gọi hàm)
    model_kwargs=kwargs_gine,    # Truyền tham số khởi tạo
    data=data,
    device=device,
    class_weights=class_weights,  # Tensor class_weights đã tính trước đó
    n_runs=5,
    epochs=1000,
    patience=100,
    lr=0.001,
    weight_decay=5e-4,
    save_path=path_gine
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.utils import degree
from torch_geometric.nn import PNAConv

# ==========================================
# 4. PNA CLASSIFIER (Principal Neighbourhood Aggregation)
# ==========================================
class PNAClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, deg, num_classes=2):
        super().__init__()
        aggregators = ['mean', 'min', 'max', 'std']
        scalers = ['identity', 'amplification', 'attenuation']

        self.conv1 = PNAConv(
            in_channels=in_channels, out_channels=32,
            aggregators=aggregators, scalers=scalers, deg=deg,
            edge_dim=1, towers=1, pre_layers=1, post_layers=1
        )

        self.conv2 = PNAConv(
            in_channels=32, out_channels=embedding_dim,
            aggregators=aggregators, scalers=scalers, deg=deg,
            edge_dim=1, towers=1, pre_layers=1, post_layers=1
        )

        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Tương tự GINE, PNA cần edge_attr 2D float
        if edge_attr is not None:
            if edge_attr.dim() == 1:
                edge_attr = edge_attr.view(-1, 1)
            edge_attr = edge_attr.float()

        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


from torch_geometric.utils import degree
row, col = data.edge_index
deg = degree(row, data.num_nodes, dtype=torch.long)
deg_histogram = torch.bincount(deg)

kwargs_pna = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'deg': deg_histogram, # Truyền tham số Deg riêng của PNA
    'num_classes': 4
}

path_pna = folder_path + 'best_pna_model.pth'

# 3. Gọi hàm bình thường
df_pna, mean_pna, std_pna = run_repeated_gnn_experiments(
    model_class=PNAClassifier, # Class PNA của bạn
    model_kwargs=kwargs_pna,
    data=data,
    device=device,
    class_weights=class_weights,
    n_runs=5,
    patience=100,
    lr=0.001,
    weight_decay=5e-4,
    save_path=path_pna
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 5. TRANSFORMER CLASSIFIER (Graph Transformer)
# ==========================================
class TransformerClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # --- LAYER 1 ---
        self.conv1 = TransformerConv(in_channels, 32, heads=4, dropout=0.3, edge_dim=1)

        # --- LAYER 2 ---
        self.conv2 = TransformerConv(32 * 4, embedding_dim, heads=1, concat=False, dropout=0.3, edge_dim=1)

        # --- CLASSIFICATION HEAD ---
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


kwargs_trans = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_trans = folder_path + 'best_transformer_model.pth'

# 3. Gọi hàm bình thường
df_pna, mean_pna, std_pna = run_repeated_gnn_experiments(
    model_class=TransformerClassifier, # Class PNA của bạn
    model_kwargs=kwargs_trans,
    data=data,
    device=device,
    class_weights=class_weights,
    n_runs=5,
    patience=100,
    lr=0.001,
    weight_decay=5e-4,
    save_path=path_trans
)



"""## GNN + ML"""

!pip install git+https://github.com/ZiyaoLi/fast-kan.git

import time
import copy
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

divice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

try:
    from fastkan import FastKAN
except ImportError:
    print("⚠️ Chưa cài đặt FastKAN. Chạy: !pip install git+https://github.com/ZiyaoLi/fast-kan.git")

# Cố định Seed
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def extract_universal_embeddings(gnn_model, data, device, model_path):
    print(f"📥 Đang nạp trọng số GNN từ: {model_path}")
    gnn_model.load_state_dict(torch.load(model_path, map_location=device))
    gnn_model.eval()

    extracted_features = {}
    def get_activation(name):
        def hook(model, input, output):
            extracted_features[name] = output.detach().cpu().numpy()
        return hook

    handle = gnn_model.conv2.register_forward_hook(get_activation('embeddings'))
    with torch.no_grad():
        gnn_model(data.x, data.edge_index, getattr(data, 'edge_attr', None))
    handle.remove()

    X_gnn = extracted_features['embeddings']
    y_labels = data.y.cpu().numpy()

    print(f"✅ Đã trích xuất Universal Embeddings: {X_gnn.shape}\n")
    return X_gnn, y_labels

def run_repeated_hybrid_pipeline(
    gnn_class, gnn_kwargs, model_path, data, device, class_weights_tensor, n_runs=5
):
    print("="*90)
    print(f"🚀 BẮT ĐẦU TỔ HỢP 2 (EARLY/LATE FUSION) - ĐÁNH GIÁ THEO TỪNG MÔ HÌNH")
    print("="*90)

    # 1. TRÍCH XUẤT EMBEDDINGS
    gnn_model = gnn_class(**gnn_kwargs).to(device)
    X_gnn, y_labels = extract_universal_embeddings(gnn_model, data, device, model_path)

    # Data Prep
    train_idx, test_idx = data.train_mask.cpu().numpy(), data.test_mask.cpu().numpy()
    X_train, y_train = X_gnn[train_idx], y_labels[train_idx]
    X_test, y_test = X_gnn[test_idx], y_labels[test_idx]

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    cw_np = class_weights_tensor.cpu().numpy()
    class_weight_dict = {i: cw_np[i] for i in range(len(cw_np))}
    sample_weights = np.array([class_weight_dict[label] for label in y_train])
    class_names = ['0_BENIGN', '1_LOW_RISK', '2_HIGH_RISK', '3_MALICIOUS']

    seeds = [42, 123, 999, 2024, 777][:n_runs]
    model_names = ["1. KNN", "2. Linear SVC", "3. Random Forest", "4. XGBoost", "5. FastKAN"]
    final_summary = []

    # Chuẩn bị Tensor cho FastKAN (Tránh ép kiểu lại nhiều lần trong loop)
    X_tensor_train = torch.tensor(X_train_scaled, dtype=torch.float32).to(device)
    y_tensor_train = torch.tensor(y_train, dtype=torch.long).to(device)
    X_tensor_test = torch.tensor(X_test_scaled, dtype=torch.float32).to(device)
    y_tensor_test = torch.tensor(y_test, dtype=torch.long).to(device)

    # 2. CHẠY LẦN LƯỢT TỪNG MÔ HÌNH
    for model_name in model_names:
        print("\n" + "="*80)
        print(f"⚙️ ĐÁNH GIÁ MÔ HÌNH: {model_name} ({n_runs} Lần chạy)")
        print("="*80)

        run_metrics = []
        run_cms = []

        for i, seed in enumerate(seeds):
            set_seed(seed)

            # --- KHỞI TẠO VÀ HUẤN LUYỆN MÔ HÌNH ---
            if model_name == "1. KNN":
                model = KNeighborsClassifier(n_neighbors=5, weights='distance')
                model.fit(X_train_scaled, y_train)
                preds = model.predict(X_test_scaled)

            elif model_name == "2. Linear SVC":
                model = LinearSVC(class_weight=class_weight_dict, max_iter=3000, random_state=seed)
                model.fit(X_train_scaled, y_train)
                preds = model.predict(X_test_scaled)

            elif model_name == "3. Random Forest":
                model = RandomForestClassifier(n_estimators=100, class_weight=class_weight_dict, random_state=seed)
                model.fit(X_train_scaled, y_train)
                preds = model.predict(X_test_scaled)

            elif model_name == "4. XGBoost":
                model = xgb.XGBClassifier(objective='multi:softprob', num_class=4, eval_metric='mlogloss', random_state=seed)
                model.fit(X_train_scaled, y_train, sample_weight=sample_weights, verbose=False)
                preds = model.predict(X_test_scaled)

            elif model_name == "5. FastKAN":
                kan_model = FastKAN([X_train_scaled.shape[1], 32, 4]).to(device)
                optimizer = optim.AdamW(kan_model.parameters(), lr=1e-3, weight_decay=1e-4)
                criterion = nn.CrossEntropyLoss(weight=class_weights_tensor.to(device))

                best_kan_f1 = 0
                preds = None # Biến lưu prediction tốt nhất

                for epoch in range(200):
                    kan_model.train()
                    optimizer.zero_grad()
                    loss = criterion(kan_model(X_tensor_train), y_tensor_train)
                    loss.backward()
                    optimizer.step()

                    kan_model.eval()
                    with torch.no_grad():
                        current_preds = kan_model(X_tensor_test).argmax(dim=1).cpu().numpy()
                        f1_val = f1_score(y_test, current_preds, average='macro', zero_division=0)
                        if f1_val > best_kan_f1:
                            best_kan_f1 = f1_val
                            preds = current_preds.copy() # Lưu lại array của epoch tốt nhất

            # --- TÍNH CHỈ SỐ CHO LẦN CHẠY NÀY ---
            acc = accuracy_score(y_test, preds)
            prec = precision_score(y_test, preds, average='macro', zero_division=0)
            rec = recall_score(y_test, preds, average='macro', zero_division=0)
            f1 = f1_score(y_test, preds, average='macro', zero_division=0)
            cm = confusion_matrix(y_test, preds)

            run_metrics.append({"Accuracy": acc, "Precision": prec, "Recall": rec, "F1-Score": f1})
            run_cms.append(cm)

            print(f" Lần chạy {i+1} (Seed {seed:<4}) | Acc: {acc:.4f} | Prec: {prec:.4f} | Rec: {rec:.4f} | F1-Score: {f1:.4f}")

        # --- VẼ GRID CONFUSION MATRIX CHO TỪNG LẦN CHẠY ---
        print(f"\n Hiển thị Confusion Matrix của {n_runs} lần chạy:")
        fig, axes = plt.subplots(1, n_runs, figsize=(3.5 * n_runs, 3))
        cmap_color = 'Blues' if 'KNN' in model_name else ('Greens' if 'SVC' in model_name else ('Oranges' if 'Forest' in model_name else ('Reds' if 'XGB' in model_name else 'Purples')))

        for idx, ax in enumerate(axes):
            sns.heatmap(run_cms[idx], annot=True, fmt='d', cmap=cmap_color, cbar=False,
                        xticklabels=['0', '1', '2', '3'], yticklabels=['0', '1', '2', '3'] if idx==0 else False,
                        annot_kws={"size": 10}, ax=ax)
            ax.set_title(f"Lần chạy {idx+1}")
            if idx == 0:
                ax.set_ylabel('True Label')
            ax.set_xlabel('Predicted Label')

        plt.tight_layout()
        plt.show()

        # --- TỔNG HỢP TRUNG BÌNH CỦA MÔ HÌNH ---
        df_model = pd.DataFrame(run_metrics)
        mean_vals = df_model.mean()
        std_vals = df_model.std()

        print(f"🌟 KẾT QUẢ TRUNG BÌNH ({model_name}):")
        print(f"   Accuracy : {mean_vals['Accuracy']:.4f} ± {std_vals['Accuracy']:.4f}")
        print(f"   Precision: {mean_vals['Precision']:.4f} ± {std_vals['Precision']:.4f}")
        print(f"   Recall   : {mean_vals['Recall']:.4f} ± {std_vals['Recall']:.4f}")
        print(f"   F1-Score : {mean_vals['F1-Score']:.4f} ± {std_vals['F1-Score']:.4f}")

        final_summary.append({
            "Mô hình": model_name,
            "Accuracy": f"{mean_vals['Accuracy']:.4f} ± {std_vals['Accuracy']:.4f}",
            "Macro Precision": f"{mean_vals['Precision']:.4f} ± {std_vals['Precision']:.4f}",
            "Macro Recall": f"{mean_vals['Recall']:.4f} ± {std_vals['Recall']:.4f}",
            "Macro F1-Score": f"{mean_vals['F1-Score']:.4f} ± {std_vals['F1-Score']:.4f}",
            "Mean F1 (Raw)": mean_vals['F1-Score']
        })

    # 3. HIỂN THỊ BẢNG SO SÁNH TỔNG QUÁT (LEADERBOARD)
    df_leaderboard = pd.DataFrame(final_summary).sort_values(by="Mean F1 (Raw)", ascending=False).drop(columns=["Mean F1 (Raw)"]).reset_index(drop=True)

    print("\n" + "="*100)
    print(f"🏆 BẢNG TỔNG HỢP SO SÁNH HIỆU NĂNG CÁC MÔ HÌNH ML (TRUNG BÌNH {n_runs} LẦN CHẠY) 🏆")
    print("="*100)
    display(df_leaderboard)

    return df_leaderboard

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 1. GAT CLASSIFIER (Graph Attention Network)
# ==========================================
class GATClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # --- LAYER 1 ---
        self.conv1 = GATConv(in_channels, 32, heads=4, dropout=0.3, edge_dim=1)

        # --- LAYER 2 ---
        self.conv2 = GATConv(32 * 4, embedding_dim, heads=1, concat=False, dropout=0.3, edge_dim=1)

        # --- CLASSIFICATION HEAD ---
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Trích xuất đặc trưng (Embedding)
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        # Phân loại (Classification)
        out = self.classifier(x)
        return out


kwargs_gat = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_gat = folder_path + 'best_gat_model.pth'

df_hybrid_gine = run_repeated_hybrid_pipeline(
    gnn_class=GATClassifier,
    gnn_kwargs=kwargs_gat,
    model_path=path_gat,
    data=data,
    device=device,
    class_weights_tensor=class_weights,
    n_runs=5
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

# ==========================================
# 2. GCN CLASSIFIER (Graph Convolutional Network)
# ==========================================
class GCNClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # GCN không có heads hay edge_dim
        self.conv1 = GCNConv(in_channels, 32)
        self.conv2 = GCNConv(32, embedding_dim)
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Biến đổi edge_attr từ 2D sang 1D cho GCN
        edge_weight = edge_attr.squeeze() if edge_attr is not None else None

        x = self.conv1(x, edge_index, edge_weight=edge_weight)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_weight=edge_weight)

        out = self.classifier(x) # Corrected: return output from classifier
        return out


kwargs_gcn = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_gcn = folder_path + 'best_gcn_model.pth'

df_hybrid_gcn = run_repeated_hybrid_pipeline(
    gnn_class=GCNClassifier,
    gnn_kwargs=kwargs_gcn,
    model_path=path_gcn,
    data=data,
    device=device,
    class_weights_tensor=class_weights,
    n_runs=5,
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 3. GINE CLASSIFIER (Graph Isomorphism Network w/ Edges)
# ==========================================
class GINEClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # Layer 1 MLP
        mlp1 = nn.Sequential(
            nn.Linear(in_channels, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU()
        )
        self.conv1 = GINEConv(nn=mlp1, train_eps=True, edge_dim=1)

        # Layer 2 MLP
        mlp2 = nn.Sequential(
            nn.Linear(128, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, embedding_dim)
        )
        self.conv2 = GINEConv(nn=mlp2, train_eps=True, edge_dim=1)

        # Classification Head
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Ép kiểu ma trận 2D và float cho edge_attr của GINE
        if edge_attr is not None:
            if edge_attr.dim() == 1:
                edge_attr = edge_attr.view(-1, 1)
            edge_attr = edge_attr.float()

        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.dropout(x, p=0.3, training=self.training)
        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


kwargs_gine = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_gine = folder_path + 'best_gine_model.pth'

df_hybrid_gine = run_repeated_hybrid_pipeline(
    gnn_class=GINEClassifier,
    gnn_kwargs=kwargs_gine,
    model_path=path_gine,
    data=data,
    device=device,
    class_weights_tensor=class_weights,
    n_runs=5
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 4. PNA CLASSIFIER (Principal Neighbourhood Aggregation)
# ==========================================
class PNAClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, deg, num_classes=2):
        super().__init__()
        aggregators = ['mean', 'min', 'max', 'std']
        scalers = ['identity', 'amplification', 'attenuation']

        self.conv1 = PNAConv(
            in_channels=in_channels, out_channels=32,
            aggregators=aggregators, scalers=scalers, deg=deg,
            edge_dim=1, towers=1, pre_layers=1, post_layers=1
        )

        self.conv2 = PNAConv(
            in_channels=32, out_channels=embedding_dim,
            aggregators=aggregators, scalers=scalers, deg=deg,
            edge_dim=1, towers=1, pre_layers=1, post_layers=1
        )

        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        # Tương tự GINE, PNA cần edge_attr 2D float
        if edge_attr is not None:
            if edge_attr.dim() == 1:
                edge_attr = edge_attr.view(-1, 1)
            edge_attr = edge_attr.float()

        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


from torch_geometric.utils import degree
row, col = data.edge_index
deg = degree(row, data.num_nodes, dtype=torch.long)
deg_histogram = torch.bincount(deg)

kwargs_pna = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'deg': deg_histogram, # Truyền tham số Deg riêng của PNA
    'num_classes': 4
}

path_pna = folder_path + 'best_pna_model.pth'

df_hybrid_gine = run_repeated_hybrid_pipeline(
    gnn_class=PNAClassifier,
    gnn_kwargs=kwargs_pna,
    model_path=path_pna,
    data=data,
    device=device,
    class_weights_tensor=class_weights,
    n_runs=5
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv, GCNConv, GINEConv, PNAConv, TransformerConv

# ==========================================
# 5. TRANSFORMER CLASSIFIER (Graph Transformer)
# ==========================================
class TransformerClassifier(torch.nn.Module):
    def __init__(self, in_channels, embedding_dim, num_classes=2):
        super().__init__()
        # --- LAYER 1 ---
        self.conv1 = TransformerConv(in_channels, 32, heads=4, dropout=0.3, edge_dim=1)

        # --- LAYER 2 ---
        self.conv2 = TransformerConv(32 * 4, embedding_dim, heads=1, concat=False, dropout=0.3, edge_dim=1)

        # --- CLASSIFICATION HEAD ---
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        x = self.conv2(x, edge_index, edge_attr=edge_attr)

        out = self.classifier(x)
        return out


kwargs_t = {
    'in_channels': data.num_features,
    'embedding_dim': 16,
    'num_classes': 4
}

path_t = folder_path + 'best_t_model.pth'

df_hybrid_gine = run_repeated_hybrid_pipeline(
    gnn_class=TransformerClassifier,
    gnn_kwargs=kwargs_t,
    model_path=path_t,
    data=data,
    device=device,
    class_weights_tensor=class_weights,
    n_runs=5
)

